"""Create core entities: orgs, users, items, sources, media_assets

Revision ID: e81ea979110f
Revises:
Create Date: 2025-08-30 07:57:04.162561

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e81ea979110f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
